"""initial schema

Revision ID: 5256e7328bfb
Revises: 
Create Date: 2026-06-12 20:47:54.191985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5256e7328bfb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_submissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('submission_date', sa.Date(), nullable=False),
    sa.Column('shift', sa.Integer(), nullable=False),
    sa.Column('records_count', sa.Integer(), nullable=True),
    sa.Column('oe_value', sa.Float(), nullable=True),
    sa.Column('machine_count', sa.Integer(), nullable=True),
    sa.Column('total_units', sa.Integer(), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('imported_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('accepted_rows', sa.Integer(), nullable=True),
    sa.Column('rejected_rows', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('file_hash', sa.Text(), nullable=True),
    sa.Column('processed_rows', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_hash')
    )
    op.create_table('production_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('csv_row_number', sa.Integer(), nullable=True),
    sa.Column('tarih', sa.Date(), nullable=False),
    sa.Column('is_emri_no', sa.Text(), nullable=True),
    sa.Column('is_merkezi_no', sa.Text(), nullable=True),
    sa.Column('ismerkezi_adi', sa.Text(), nullable=True),
    sa.Column('is_istasyon_adi', sa.Text(), nullable=True),
    sa.Column('stok_adi', sa.Text(), nullable=True),
    sa.Column('vardiya', sa.Integer(), nullable=True),
    sa.Column('availability', sa.Float(), nullable=True),
    sa.Column('performance', sa.Float(), nullable=True),
    sa.Column('quality', sa.Float(), nullable=True),
    sa.Column('oee', sa.Float(), nullable=True),
    sa.Column('calisma_suresi', sa.Float(), nullable=True),
    sa.Column('durus_suresi', sa.Float(), nullable=True),
    sa.Column('planli_durus', sa.Float(), nullable=True),
    sa.Column('plansiz_durus', sa.Float(), nullable=True),
    sa.Column('uretilen_miktar', sa.Integer(), nullable=True),
    sa.Column('hatali_miktar', sa.Integer(), nullable=True),
    sa.Column('validation_status', sa.Text(), nullable=False),
    sa.Column('is_sent', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('validation_issues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('rule_code', sa.Text(), nullable=False),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('field_name', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('suggested_action', sa.Text(), nullable=True),
    sa.Column('resolved', sa.Integer(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.Text(), nullable=True),
    sa.Column('correction_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['production_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('validation_issues')
    op.drop_table('production_records')
    op.drop_table('import_batches')
    op.drop_table('api_submissions')
    # ### end Alembic commands ###
